server:
  port: 8089  # Changed from 8080 to 8089 as requested

spring:
  application:
    name: CityBus Tracker

jwt:
  secret: ${JWT_SECRET:your_super_secret_key_change_this_in_production_must_be_at_least_256_bits_long_for_security}

logging:
  level:
    com.citybus: DEBUG
    org.springframework.security: INFO
    org.springframework.web.socket: INFO